[project]
name = 'Tokenized-Intellectual-Property-Patent-Portfolio-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.infringement-monitoring]
path = 'contracts/infringement-monitoring.clar'
clarity_version = 2
epoch = 2.5

[contracts.ip-attorney-verification]
path = 'contracts/ip-attorney-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
